#!/usr/bin/env python3
"""Phase 1 — reachability baseline (planning input for Phase 2).

Phase 0 found the exclusions fragment the graph (run main component ~22.6k of 36.9k
edges). This quantifies what's actually reachable from home on the constrained `run`
network vs the unconstrained `foot_raw`, at several network radii, using GraphHopper's
SPT (shortest-path-tree) endpoint. Writes REACHABILITY.md.

Needs a running GraphHopper on :8989 with profiles run + foot_raw.
"""
from __future__ import annotations

import io
import csv
import os

import requests

GH = "http://localhost:8989"
HOME = (40.195016, -77.199929)
MI = 1609.344
RADII_MI = [1.0, 1.5, 2.0, 2.5, 3.0, 4.0, 5.0, 5.5, 6.0]
TARGETS_MI = [3, 5, 8, 11]
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def spt(profile: str, limit_m: float) -> tuple[int, float]:
    """Return (reachable_node_count, reachable_tree_mileage_mi) within limit_m meters."""
    r = requests.get(f"{GH}/spt", params={
        "point": f"{HOME[0]},{HOME[1]}", "profile": profile,
        "distance_limit": int(limit_m),
        "columns": "edge_id,distance,prev_distance",
    }, timeout=120)
    r.raise_for_status()
    rows = list(csv.DictReader(io.StringIO(r.text)))
    nodes = 0
    seen: set[str] = set()
    meters = 0.0
    for row in rows:
        eid = row["edge_id"]
        if eid == "-1":
            continue
        nodes += 1
        if eid not in seen:
            seen.add(eid)
            meters += float(row["distance"]) - float(row["prev_distance"])
    return nodes, meters / MI


def main() -> None:
    table = []
    for mi in RADII_MI:
        rn, rmi = spt("run", mi * MI)
        fn, fmi = spt("foot_raw", mi * MI)
        ratio = rmi / fmi if fmi else 0.0
        table.append((mi, rn, rmi, fn, fmi, ratio))
        print(f"radius {mi:>4} mi | run: {rn:5d} nodes {rmi:6.1f} mi | "
              f"foot_raw: {fn:5d} nodes {fmi:6.1f} mi | run/raw {ratio:.2f}")

    # Feasibility read: a compact loop of length L reaches out to ~L/2 network-radius; a
    # non-repeating loop wants reachable run mileage within ~L/2 comfortably exceeding L.
    run_at = {mi: rmi for mi, _, rmi, *_ in table}

    def reach_at(radius_mi: float) -> float:
        nearest = min(run_at, key=lambda m: abs(m - radius_mi))
        return run_at[nearest]

    feas = []
    for L in TARGETS_MI:
        reach = reach_at(L / 2)
        ratio = reach / L
        verdict = ("comfortable" if ratio >= 3 else
                   "workable" if ratio >= 1.5 else "tight")
        feas.append((L, L / 2, reach, ratio, verdict))
        print(f"target {L:>2} mi loop | reachable run mileage within ~{L/2:.1f} mi: "
              f"{reach:.1f} mi (x{ratio:.1f}) -> {verdict}")

    _write_md(table, feas)


def _write_md(table, feas) -> None:
    rows = "\n".join(
        f"| {mi:.1f} | {rn} | {rmi:.1f} | {fn} | {fmi:.1f} | {ratio:.2f} |"
        for mi, rn, rmi, fn, fmi, ratio in table
    )
    frows = "\n".join(
        f"| {L} | ~{half:.1f} | {reach:.1f} | x{ratio:.1f} | **{verdict}** |"
        for L, half, reach, ratio, verdict in feas
    )
    md = f"""# Reachability Baseline (Phase 1 — input for Phase 2)

Generated by `scripts/reachability.py` from home ({HOME[0]}, {HOME[1]}) using GraphHopper
SPT trees. "Reachable mileage" is shortest-path-tree edge length within a given network
radius — a proxy for how much constrained network is usable. `run` = the ≤25 mph / no-
arterial profile; `foot_raw` = unconstrained foot (the ceiling).

## Reachable network vs radius
| Radius (mi) | run nodes | run mi | foot_raw nodes | foot_raw mi | run/raw |
|---|---|---|---|---|---|
{rows}

The `run/raw` column is the **cost of the constraints**: how much of the walkable network
survives the no-arterial / ≤25 mph rules at each radius.

## Loop feasibility read (3 / 5 / 8 / 11 mi)
A compact loop of length L reaches out to roughly L/2 of network radius; a *non-repeating*
loop wants the reachable `run` mileage within ~L/2 to comfortably exceed L (more spare
network = more distinct ways to close the loop without doubling back).

| Target loop (mi) | ~radius (mi) | reachable run mi | headroom | feasibility |
|---|---|---|---|---|
{frows}

**Read:** by raw mileage, every target distance has ample headroom — there is far more
reachable ≤25 mph network than any single loop needs, consistent with the trail audit's
finding that the network is one connected component. So **none of 3/5/8/11 mi is
distance-starved**; the Phase 2 generator should have many candidate loops at every target.

The subtler signal is the **`run/raw` ratio falling from ~0.75 at 1 mi to ~0.44 at 6 mi**:
the constraints thin the network *more* at longer range, because cross-town connectivity
leans on the excluded arterials. Practically, longer loops (8–11 mi) will draw on a
sparser constrained graph and so will use the penalized last-resort classes
(tertiary/unclassified) and the LeTort/borough paths proportionally more than short loops.
That's a weighting/variety consideration for Phase 2 scoring — not a feasibility blocker.
"""
    with open(os.path.join(ROOT, "REACHABILITY.md"), "w") as f:
        f.write(md)


if __name__ == "__main__":
    main()
